[font]
size = 17

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "Buttonless"

[window.padding]
x = 7
y = 0

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[terminal]

[terminal.shell]
program = "tmux"

