[font]
size = 20

[font.normal]
family = "Iosevka Nerd Font"

[window]
decorations = "Buttonless"

[window.padding]
x = 7
y = 0

[general]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

